#ifndef LIBCOMMARDUINO_GLOBAL_H
#define LIBCOMMARDUINO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBCOMMARDUINO_LIBRARY)
#  define LIBCOMMARDUINOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBCOMMARDUINOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBCOMMARDUINO_GLOBAL_H
